### ISSUE TITLE
Provide a way to set additional environment variables

### ISSUE THREAD

**Issue by mmenozzi** [igorw/CgiHttpKernel#8]
Hi Igor,
first of all congratulations for your library. It's great.

Only a small issue. I think that there should be a way to set additional environment variables on the ProcessBuilder before starting it.

I think so because I'm using CgiHttpKernel for Magento's functional tests and I need to set a Magento-specific $_SERVER variable (MAGE_IS_DEVELOPER_MODE). If I set it on my request this is not passed to the process as environment variable because in CgiHttpKernel::handle() only a subset of $_SERVER variables are set.

I can do this and make a PR but first I want your opinion. How we can do that? Calling a closure?
Bye.

**Comment by igorw** [comment]
Should be fixed. The latest version allows you to set custom vars through the request object:

```
$request = Request::create('/foo');
$request->server->set('MAGE_IS_DEVELOPER_MODE', 'true');
$response = $app->handle($request);
```

I hope this works for you!

**Comment by mmenozzi** [comment]
Yes! With your last command all SERVER variables on Request will be passed to the ProcessBuilder. I already tested it on my current project and it works!

Thank you very much!
